apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: cloudnative-pg
  app.kubernetes.io/component: manager
resources:
  - ../configurations/prometheus-operator
  - clusterrole.yaml
  - clusterrole-edit.yaml
  - deployment.yaml
  - lease.yaml
  - monitor.yaml
  - pdb.yaml
  - rbac.yaml
  - role.yaml
  - service.yaml
  - mutatingwebhookconfiguration.yaml
  - validatingwebhookconfiguration.yaml
configMapGenerator:
  - name: manager-config
    options:
      disableNameSuffixHash: true
  - name: default-monitoring
    options:
      disableNameSuffixHash: true
      labels:
        cnpg.io/reload: ""
    files:
      - queries=files/queries.yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: manager
      spec:
        template:
          spec:
            containers:
              - name: manager
                env:
                  - name: POSTGRES_IMAGE_NAME
                    # renovate: datasource=docker
                    value: ghcr.io/cloudnative-pg/postgresql:17.6@sha256:175ccb714d18eacf236658c4403a9e686212e837c605a1d9bcd5b68c7dc4c9a7
images:
  - name: ghcr.io/cloudnative-pg/cloudnative-pg
    newTag: 1.27.0@sha256:9e5633b36f1f3ff0bb28b434ce51c95fbb8428a4ab47bc738ea403eb09dbf945
replacements:
  - source:
      kind: Deployment
      name: manager
      fieldPath: spec.template.spec.containers.[name=manager].image
    targets:
      - select:
          kind: Deployment
          name: manager
        fieldPaths:
          - spec.template.spec.containers.[name=manager].env.[name=OPERATOR_IMAGE_NAME].value
