apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: cloudnative-pg
resources:
  - ../../configurations/clusterimagecatalog
  - github.com/cloudnative-pg/postgis-containers/image-catalogs?ref=025b8bc9f5b2d16d08c94546be26bfec82039636 # branch=main
