apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: cloudnative-pg
resources:
  - ../../configurations/clusterimagecatalog
  - github.com/cloudnative-pg/postgis-containers/image-catalogs?ref=54ad2085161f8f35645e3871874ebaa9b25fc51b # branch=main
