apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: cloudnative-pg
resources:
  - ../../configurations/clusterimagecatalog
  - github.com/cloudnative-pg/artifacts/image-catalogs?ref=a13fc2381ccd7ae50475481394651df634bd8549 # branch=main
