apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: cloudnative-pg
resources:
  - ../../configurations/clusterimagecatalog
  - github.com/cloudnative-pg/artifacts/image-catalogs?ref=28feea3ecab43ad1cb3d03dfe28f24116ba9d896 # branch=main
