apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: cloudnative-pg
resources:
  - ../../configurations/clusterimagecatalog
  - github.com/cloudnative-pg/artifacts/image-catalogs?ref=f7f13c3b03c47f547f449408ea0aef9ac2bbce64 # branch=main
