apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - patch: |
      apiVersion: policy/v1
      kind: PodDisruptionBudget
      metadata:
        name: manager
      spec:
        minAvailable: 1
replicas:
  - name: manager
    count: 2
